image: node:14

stages:
  - yarn
  - test
  - pages

yarn:
  stage: yarn
  script:
    - yarn install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - yarn
  script:
    - yarn format
    - yarn lint
    - yarn test

pages:
  stage: pages
  dependencies:
    - yarn
  script:
    - yarn build-storybook
  artifacts:
    paths:
      - public
  only:
    - main
