image: node:14

cache:
  paths:
    - ./node_modules

pages:
  stage: deploy
  before_script:
    - yarn install
  script:
    - yarn build-storybook
  artifacts:
    paths:
      - public
  only:
    - main
