name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    name: Send a tweet
    runs-on: ubuntu-latest

    steps:
      - name: Send tweet
        run: echo "TWEET_TEXT=A new version of $PROJECT_NAME was released - $GITHUB_REF '#reactnative '#typescript '#javascript '#developer $GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV
      - uses: ethomson/send-tweet-action@v1.0.0
        with:
          status: ${{ env.TWEET_TEXT }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        env:
          PROJECT_NAME: Template Expo with React Native Paper
